global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'contracts-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['contracts-api:3001']

  - job_name: 'flash-sales-api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['flash-sales-api:3002']
